### ISSUE TITLE
Support for RxJava2

### ISSUE THREAD

**Issue by Savrov** [saantiaguilera/android-api-RxFacebook#3]
Hello, i'm getting an error:
![eventremoterepository_kt_-_tonight_-____documents_workspacemobile_tonight__-_android_studio_3_0_canary_5](https://user-images.githubusercontent.com/5410076/27924608-2f772d04-6282-11e7-8f2c-62fbafd27704.png)

I found out that you are using "old" libs:  io.reactivex.rxjava and io.reactive.rxandroid
can you add a support for **io.reactivex.rxjava2** & **io.reactive.rxandroid2**, please?
Thank you.

**Comment by saantiaguilera** [comment]
Done, version 2.0.0 released with Rx2 module that gives support to it :)

**Comment by Savrov** [comment]
hmmm. can't resolve the dependency

**Comment by saantiaguilera** [comment]
Ah, sorry its because its not yet in jcenter. As soon as they email me I answer you here :)

For now you can add to your allprojects closure:
```
allprojects {
  maven {
    url 'https://dl.bintray.com/saantiaguilera/maven/'
  }
}
```

And it should find it :)

**Comment by Savrov** [comment]
Great! Thank you

**Comment by saantiaguilera** [comment]
Its on jcenter also :) So you dont need anymore the maven url
